wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.10.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684137572.24429
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.5
      5: 0.15.2
      6: 4.10.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: warmup+decay
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
model_name:
  desc: null
  value: klue/roberta-large
lr:
  desc: null
  value: 1.0e-05
num_labels:
  desc: null
  value: 30
warmup_steps:
  desc: null
  value: 500
max_training_step:
  desc: null
  value: 9000
loss_type:
  desc: null
  value: focal
classifier:
  desc: null
  value: default
lr_decay:
  desc: null
  value: default
